/*
When visualizing a query, it's helpful to imagine the full table generated by
the FROM clause (with the JOINs), similar to what you saw above.  Then the WHERE
clause is limiting which rows are returned from that table, and the SELECT clause
is limiting which columns are returned (and renaming them as needed).
*/
SELECT it.name, inv.price, inv.quantity, l.name as location
FROM inventory inv
JOIN item it ON inv.item_id = it.id
JOIN location l ON inv.location_id = l.id
WHERE inv.quantity < 10
;

/*
Here we are returning just some basic columns of information, and only for items where the
inventory is small (< 10 items at a location). Again, this is all gleaned from the raw table
we saw before.
*/

